version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    env_file: .env
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 1323:1323
    depends_on:
      - test_db
  test_db:
    build: ./db_test/
    platform: linux/x86_64 # for M1 chip
    image: mysql:8.0
    container_name: db-test-container
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: sample_blog_test
      MYSQL_USER: test_blogger
      MYSQL_PASSWORD: tset_reggolb
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-test-data:/var/lib/mysql
    ports:
      - 3307:3307

volumes:
  db-test-data:
    driver: local
