# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          command: |
            sudo add-apt-repository -y ppa:longsleep/golang-backports
            sudo apt update -y 
            sudo apt install -y golang-go
      - run:
          name: docker compose build
          command: docker compose -f docker-compose-test.yml build
      - run:
          name: docker compose up
          command: docker compose -f docker-compose-test.yml up -d
      - run:
          name: test
          command: |
            docker compose ps
            docker compose exec app go test -v
      - run:
          name: docker compose down
          command: docker compose down

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
