# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run: sudo apt-get update 
      - run:
          name: docker compose build
          command: docker compose build --no-cache
      - run:
          name: docker compose up
          command: docker compose up -d
      - run:
          name: test
          command: |
            docker compose ps
            docker-compose exec app go test -v
      - run:
          name: docker compose down
          command: docker compose down

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
