package cron

import (
	"context"
	"encoding/json"
	"fmt"
	"io/ioutil"
	"log"
	"net/http"
	"os"
	"runtime"
	"time"

	"github.com/robfig/cron/v3"
)

type AutoGenerated struct {
	Sys struct {
		Type string `json:"type"`
	} `json:"sys"`
	Total int `json:"total"`
	Skip  int `json:"skip"`
	Limit int `json:"limit"`
	Items []struct {
		Metadata struct {
			Tags []interface{} `json:"tags"`
		} `json:"metadata"`
		Sys struct {
			Space struct {
				Sys struct {
					Type     string `json:"type"`
					LinkType string `json:"linkType"`
					ID       string `json:"id"`
				} `json:"sys"`
			} `json:"space"`
			ID          string    `json:"id"`
			Type        string    `json:"type"`
			CreatedAt   time.Time `json:"createdAt"`
			UpdatedAt   time.Time `json:"updatedAt"`
			Environment struct {
				Sys struct {
					ID       string `json:"id"`
					Type     string `json:"type"`
					LinkType string `json:"linkType"`
				} `json:"sys"`
			} `json:"environment"`
			Revision    int `json:"revision"`
			ContentType struct {
				Sys struct {
					Type     string `json:"type"`
					LinkType string `json:"linkType"`
					ID       string `json:"id"`
				} `json:"sys"`
			} `json:"contentType"`
			Locale string `json:"locale"`
		} `json:"sys"`
		Fields struct {
			Title string `json:"title"`
			Body  struct {
				Data struct {
				} `json:"data"`
				Content []struct {
					Data struct {
					} `json:"data"`
					Content []struct {
						Data struct {
						} `json:"data"`
						Marks    []interface{} `json:"marks"`
						Value    string        `json:"value"`
						NodeType string        `json:"nodeType"`
					} `json:"content"`
					NodeType string `json:"nodeType"`
				} `json:"content"`
				NodeType string `json:"nodeType"`
			} `json:"body"`
		} `json:"fields"`
	} `json:"items"`
}

func Start() {
	c := cron.New()

	c.AddFunc("@every 5m", getEntriesFromAPI)

	c.Start()

	runtime.Goexit()
}

func getEntriesFromAPI() {
	spaceId := os.Getenv("SAMPLE_BLOG_SPACE_ID")
	accessToken := os.Getenv("SAMPLE_BLOG_ACCESS_TOKEN")
	url := "https://cdn.contentful.com/spaces/" + spaceId + "/entries?access_token=" + accessToken
	getRequest(url)
}

func getRequest(url string) error {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	client := &http.Client{}
	req, _ := http.NewRequest("GET", url, nil)
	resp, err := client.Do(req.WithContext(ctx))
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalf("ioutil.ReadAll err=%s", err.Error())
	}
	jsonBytes := ([]byte)(string(body))

	data := new(AutoGenerated)
	if err := json.Unmarshal(jsonBytes, data); err != nil {
		fmt.Println("JSON Unmarshal error:", err)
		return nil
	}
	// TODO 例 後で整形する
	/**
	{サンプルブログのタイトル {{} [{{} [{{} [] 概要 text}] heading-1} {{} [{{} [] H1 text}] heading-1} {{} [{{} [] H2 text}] heading-2} {{} [{{} [] H3 text}] heading-3} {{} [{{} [] こんな感じでかけます。 text}] paragraph} {{} [{{} [map[type:bold]] 太字 text}] paragraph} {{} [{{} [map[type:bold] map[type:underline]] 下線部 text}] paragraph} {{} [{{} [map[type:code]] <h1>h1タグ, scriptなども使えます<h1> text}] paragraph} {{} [{{} [map[type:code]]  text}] paragraph} {{} [{{} [map[type:bold]]  text}] paragraph}] document}}
	*/
	fmt.Println(data.Items[0].Fields)
	return nil
}
